spring:
  application:
    name: spring-boot-mq-kafka-batch-consume
  # Kafka 配置项，对应 KafkaProperties 配置类
  kafka:
    bootstrap-servers: ${REMOTE_URL:127.0.0.1}:9092 # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
    # Kafka Producer 配置项
    producer:
      acks: 1 # 0-不应答。1-leader 应答。all-所有 leader 和 follower 应答。
      retries: 3 # 发送失败时，重试发送的次数
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 key 的序列化
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 消息的 value 的序列化
    # Kafka Consumer 配置项
    consumer:
      auto-offset-reset: earliest # 设置消费者分组最初的消费进度为 earliest ，防止消息丢失。
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      fetch-max-wait: 10000 # 一次拉取的阻塞的最大时长，单位：毫秒。这里指的是阻塞拉取需要满足至少 fetch-min-size 大小的消息
      fetch-min-size: 25600 # 一次消息拉取的最小数据量，单位：字节
      max-poll-records: 100 # 一次消息拉取的最大数量
      properties:
        spring:
          json:
            trusted:
              # 配置 信任， 不然消费时候会抛异常 is not in the trusted packages
              packages: top.bulk.mq.kafka.batch.consume.message
    # 这个配置如果配置 SINGLE ，就只会单条消费了
    listener:
      type: batch

# 日志太多了，不好看输出效果，先只打印 WARN 级别，这里是非必须的配置
logging:
  level:
    org:
      springframework:
        kafka: WARN
      apache:
        kafka: WARN