server:
  port: 8088
spring:
  application:
    name: spring-boot-mq-rabbit-batch-send
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: ${REMOTE_URL:127.0.0.1}
    port: 5672
    username: admin
    password: admin


